export const formulaTemplate = [
  { id: 18, name: "", status: "" },
  { id: 17, name: "", status: "" },
  { id: 16, name: "", status: "" },
  { id: 55, name: 55, status: "" },
  { id: 54, name: 54, status: "" },
  { id: 53, name: 53, status: "" },
  { id: 52, name: 52, status: "" },
  { id: 51, name: 51, status: "" },
  { id: 61, name: 61, status: "" },
  { id: 62, name: 62, status: "" },
  { id: 63, name: 63, status: "" },
  { id: 64, name: 64, status: "" },
  { id: 65, name: 65, status: "" },
  { id: 26, name: "", status: "" },
  { id: 27, name: "", status: "" },
  { id: 28, name: "", status: "" },
  { id: 48, name: "", status: "" },
  { id: 47, name: "", status: "" },
  { id: 46, name: "", status: "" },
  { id: 85, name: 85, status: "" },
  { id: 84, name: 84, status: "" },
  { id: 83, name: 83, status: "" },
  { id: 82, name: 82, status: "" },
  { id: 81, name: 81, status: "" },
  { id: 71, name: 71, status: "" },
  { id: 72, name: 72, status: "" },
  { id: 73, name: 73, status: "" },
  { id: 74, name: 74, status: "" },
  { id: 75, name: 75, status: "" },
  { id: 36, name: "", status: "" },
  { id: 37, name: "", status: "" },
  { id: 38, name: "", status: "" }
];
export const permanentTemplate = [
  { id: 17, name: 17, status: "" },
  { id: 16, name: 16, status: "" },
  { id: 15, name: 15, status: "" },
  { id: 14, name: 14, status: "" },
  { id: 13, name: 13, status: "" },
  { id: 12, name: 12, status: "" },
  { id: 11, name: 11, status: "" },
  { id: 21, name: 21, status: "" },
  { id: 22, name: 22, status: "" },
  { id: 23, name: 23, status: "" },
  { id: 24, name: 24, status: "" },
  { id: 25, name: 25, status: "" },
  { id: 26, name: 26, status: "" },
  { id: 27, name: 27, status: "" },
  { id: 47, name: 47, status: "" },
  { id: 46, name: 46, status: "" },
  { id: 45, name: 45, status: "" },
  { id: 44, name: 44, status: "" },
  { id: 43, name: 43, status: "" },
  { id: 42, name: 42, status: "" },
  { id: 41, name: 41, status: "" },
  { id: 31, name: 31, status: "" },
  { id: 32, name: 32, status: "" },
  { id: 33, name: 33, status: "" },
  { id: 34, name: 34, status: "" },
  { id: 35, name: 35, status: "" },
  { id: 36, name: 36, status: "" },
  { id: 37, name: 37, status: "" }
];
export const patientTemplate = [
  {
    _id: "1",
    disease: "хвороба",
    reviewDate: `1.1.2025`,
    cardNumber: `1`,
    name: `Новий Тест Батькович`,
    doctor: "Особистий лікар",
    toothCasual: "55",
    start1: "",
    start2: "день",
    pregnancy: 1,
    childbirth: 1,
    birthWeight: "3600",
    condition: "задовільний",
    weight: "55",
    age: 17,
    crownDestruction: "частково зруйнована",
    inflammationArea: "54,55",
    planned: false,
    drugs: [
      "ібупрофен, по 200 мг, двічі на добу",
      "Лоратадин, сироп, по 5 мл, 1 р/д"
    ],
    protocolNumber: "1",
    operationDate: "1.1.2021",
    operationTime: "12.00",
    pliers: "",
    elevator: "",
    duration: "15 хвилин",
    surgeon: "Хірург",
    assistant: "Асистент",
    anesthetist: "Анестезіолог",
    woundArea: "",
    woundSide: "",
    injuryDate: "",
    injuryTime: "",
    injuryReason: "",
    woundType: "",
    woundLength: "",
    woundWidth: "",
    woundDepth: "",
    woundForm: "",
    woundLedges: "",
    woundBleeding: "",
    woundAliens: "",
    sutureType: "",
    sutureMaterial: "",
    sutureSize: "",
    startDay: "",
    startMonth: "",
    startYear: "",
    operationDataSend: true,
    complaintsContent: "на біль.",
    anamnesisMorbiContent: "хворіє 1 день.",
    anamnesisVitaeContent: "пацієнт...",
    statusPraesensContent: "соматично здоровий",
    shortStatusContent: "обличчя симетричне",
    statusLocalisContent: "обличчя симетричне",
    diagnosis: "періодонтит",
    diagnosisCap: "Періодонтит",
    operationName: "видалення зуба",
    operationNameCap: "Видалення зуба",
    operationContent: "Місцеве знеболення...",
    perioTeeth: "",
    heartRate: 70,
    respiratoryRate: 20,
    lastTime: "15.00",
    someDayContent: "Обличчя симетричне...",
    lastDayContent: "Обличчя симетричне...",
    diaryList: [
      {
        date: `1.1.2025`,
        workDay: true
      },
      {
        date: `1.1.2025`,
        workDay: true
      },
      {
        date: `1.1.2025`,
        workDay: true
      }
    ],
    changedList: [1, 2, 3],
    epicrisisDataSend: false,
    extractDataSend: false,
    anestesiaType: `Загальне знеболення`,
    abscessType: "",
    abscessArea: "",
    abscessSide: "",
    abscessReason: "",
    abscessTooth: "",
    cystTooth: "",
    rootSealed: "",
    toothFormula: formulaTemplate
  }
];
